name: pipeline
on:
  push:
    branches:
      - 'deploy'
jobs:
  deploy:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the branch that triggered the workflow
      - uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push API
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: emvit/express-starter:latest
